# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='recipe',
            field=models.ForeignKey(blank=True, db_column=b'recipe', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='foody.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, db_column=b'recipe', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='foody.Recipe'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='menuItem',
            field=models.ForeignKey(blank=True, db_column=b'menuItem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='foody.MenuItem'),
        ),
    ]
