# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0002_auto_20161122_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(blank=True, default='Ball some meat', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(blank=True, default='Meatballs', max_length=100),
        ),
    ]
