# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0002_auto_20161201_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='menuItem',
        ),
        migrations.AddField(
            model_name='recipe',
            name='menuItemasda',
            field=models.ForeignKey(blank=True, db_column=b'menuItem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='foody.MenuItem'),
        ),
    ]
