# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0003_auto_20161128_2348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='direction',
            unique_together=set([('recipe', 'text')]),
        ),
    ]
