# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0004_auto_20161127_1708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directions',
            new_name='Direction',
        ),
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
