# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0004_auto_20161129_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='direction',
            unique_together=set([]),
        ),
    ]
