# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0005_auto_20161127_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='direction',
            field=models.CharField(blank=True, default=b'Stir', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.CharField(blank=True, default=b'Balls', max_length=100),
        ),
        migrations.AlterField(
            model_name='direction',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='foody.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='foody.Recipe'),
        ),
    ]
