# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0005_auto_20161202_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(blank=True, default=b'Recipe Title', max_length=100),
        ),
    ]
