# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0006_auto_20161127_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPurchased', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='foody.Ingredient'),
        ),
    ]
