# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0007_auto_20161204_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='recipe',
            field=models.ForeignKey(blank=True, db_column=b'recipe', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='foody.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, db_column=b'recipe', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='foody.Recipe'),
        ),
    ]
