# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0008_auto_20161204_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='menuItem',
            field=models.ForeignKey(blank=True, db_column=b'menuItem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe', to='foody.MenuItem'),
        ),
    ]
